### ISSUE TITLE
Perhaps let people what commands you can run when you run this? Instead of only during a help command

### ISSUE THREAD

**Issue by WolfenGames** [thatguywiththefunnyname/techSupport#6]
https://github.com/thatguywiththefunnyname/techSupport/blob/f69e22f5c65399fca78d89f3f9dc6a3096422abe/update_bot.sh#L7

Refer to title

**Comment by thatguywiththefunnyname** [comment]
Issue will be resolved in the next push, thank you for raising it.

**Comment by thatguywiththefunnyname** [comment]
Handled and fixed.
